language: python3
script: cd lab/ && make all
addons:
  apt:
    packages:
    - python3-tk
    - python3-numpy
    - python3-scipy
python:
  - "3.5"
virtualenv:
  system_site_packages: true
before_install:
  - pip install --upgrade pip setuptools wheel
install:
  - pip install --only-binary=numpy,scipy numpy scipy matplotlib scikit-learn scikit-image graphviz
  - easy_install -U pip
notifications:
    email:
          on_success: never
