language: python3
script: cd lab/ && make all
addons:
  apt:
    packages:
    - python3-tk
    - python3-numpy
    - python3-scipy

matrix:
  include:
    - python: "3.5"
      env: DEPS="scipy numpy matplotlib scikit-learn scikit-image graphviz"

virtualenv:
  system_site_packages: true
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda2/bin:$PATH
  - conda update --yes conda
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION scipy numpy matplotlib scikit-learn scikit-image graphviz
  - easy_install -U pip
notifications:
    email:
          on_success: never
