script: cd lab/ && make all
addons:
  apt:
    packages:
    - python3-tk
    - python3-numpy
    - python3-scipy

language: python3
python:
  - "3.5"
install:
  - easy_install -U pip
  - pip install scipy numpy matplotlib scikit-learn scikit-image graphviz
virtualenv:
  system_site_packages: true
notifications:
    email:
          on_success: never
