script: cd lab/ && make all
addons:
  apt:
    packages:
    - python3-tk

lgoanguage: python3
python:
  - "3.5"
install:
  - easy_install -U pip
  - pip install scipy
  - pip install numpy
  - pip install matplotlib
  - pip install scikit-learn
  - pip install scikit-image
  - pip install graphviz
notifications:
    email:
          on_success: never
