language: python3
script: cd lab/ && make all
addons:
  apt:
    packages:
    - python3-tk
    - python3-numpy
    - python3-scipy

matrix:
  include:
    - python: "3.5"
      env: DEPS="scipy numpy matplotlib scikit-learn scikit-image graphviz"
virtualenv:
  system_site_packages: true
install:
  - easy_install -U pip

notifications:
    email:
          on_success: never
