script: make all
before_script:
    - sudo apt install pip{,3} python3-tk
    - sudo pip3 install scipy numpy matplotlib scikit-{learn,image} graphviz
    - virtualenv --system-site-packages -p python3 .tf/
    - source srcactivate
    - easy_install -U pip
    - cd lab/

    # need to investigate tensorflow on ci
    # - pip3 install --upgrade tensorflow

lgoanguage: python3
python:
  - "3.5"
notifications:
    email:
          on_success: never
