= CMP-464: Neural Networks
:profhome: http://comet.lehman.cuny.edu/schneider
:basecmp464: {profhome}/Fall17/CMP464
:cmp464: {basecmp464}/index464.html
:cmp464install: {basecmp464}/SetupSoftware.pdf
:_installtf_: https://www.tensorflow.org/install/install_linux
:installtf: {_installtf_}#determine_how_to_install_tensorflow
:afterinsttf: {_installtf_}#next_steps
:validatettf: {_installtf_}#ValidateYourInstallation
:travisciuri: https://travis-ci.org/jzacsh/neuralnets-cmp464
:traviscibug: https://travis-ci.org/jzacsh/neuralnets-cmp464/builds/272568257#L693
:bd5c044fa308511fcuri: https://github.com/jzacsh/neuralnets-cmp464/commit/bd5c044fa308511fc

Personal course work for {cmp464}[CMP-464 Neural Networks] with
{profhome}[Professor Schneider] at Lehman College, Fall 2017.

== active development

When coming back to work in this repo, these steps are necessary. It is assumed
you followed <<installing, setup instructions>>

[[workingactiv]]
.working in this repo
----
$ source srcactivate
----

=== `cd ./lab/` for in-class work

Under the `./lab/` dir...

.to actively run a file via unit tests
----
$ make test # <1>
python3 lab20170905_test.py
..
 ----------------------------------------------------------------------
Ran 2 tests in 0.173s

OK
----
<1> should work on each `git push`, but {traviscibug}[travis-ci.org has proven
difficult to setup] image:{travisciuri}.svg?branch=master["Build Status",
link="{travisciuri}"]; see {bd5c044fa308511fcuri}[`bd5c044fa308511fc`] commit
message for more.

.to actively re-run a file with printf debugging
----
$ make current # default recipe
python3 lab20170905.py
rand set's cost was 0.0000000002, for minimization to: [ -2.36923935e-06  -9.99971761e-01]
----

[[installing]]
== install & setup for course or fresh clones

Below are one-time steps are necessary for working on any fresh clone of this
repo.

Installed software {cmp464install}[based on instructions]:
----
$ sudo apt install pip{,3} python3-tk
$ sudo pip3 install scipy numpy matplotlib scikit-{learn,image} graphviz
----

Following {installtf}[tensorflow's `virtualenv` recommendation]:
----
$ virtualenv --system-site-packages -p python3 .tf/
$ source srcactivate
$ easy_install -U pip
$ pip3 install --upgrade tensorflow
----

Tensorflow {afterinsttf}[docs recommends] to now validatig
{validatettf}[tesnforflow installations].

The {cmp464install}[anaconda instructions] just to help us -- will not be
switching env.s/tools for the class.

.ymmv: this all worked for *me*
----
$ uname -a
Linux garak 4.10.0-33-generic #37~16.04.1-Ubuntu SMP Fri Aug 11 14:07:24 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"
----

=== documenting what i did

This section just describes what i did to setup this repo - not to be duplicated
by cloners of this repo.

.one-time hacks for this repo
----
$ echo .tf > .gitignore
$ ln -sv .tf/bin/activate srcactivate # <1>
----
<1> <<workingactiv, bash-specific, for "active dev" section>>
